// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: order/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status enum
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_SHIPPED",
		4: "ORDER_STATUS_DELIVERED",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_SHIPPED":     3,
		"ORDER_STATUS_DELIVERED":   4,
		"ORDER_STATUS_CANCELLED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{0}
}

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCESS     PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCESS",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCESS":     2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_order_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_order_order_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{1}
}

// Payment method enum
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD  PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_PAYPAL      PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_BANK_WIRE   PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_PAYPAL",
		4: "PAYMENT_METHOD_BANK_WIRE",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CREDIT_CARD": 1,
		"PAYMENT_METHOD_DEBIT_CARD":  2,
		"PAYMENT_METHOD_PAYPAL":      3,
		"PAYMENT_METHOD_BANK_WIRE":   4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_order_proto_enumTypes[2].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_order_order_proto_enumTypes[2]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{2}
}

// Rating enum
type Rating int32

const (
	Rating_RATING_UNSPECIFIED Rating = 0
	Rating_RATING_ONE         Rating = 1
	Rating_RATING_TWO         Rating = 2
	Rating_RATING_THREE       Rating = 3
	Rating_RATING_FOUR        Rating = 4
	Rating_RATING_FIVE        Rating = 5
)

// Enum value maps for Rating.
var (
	Rating_name = map[int32]string{
		0: "RATING_UNSPECIFIED",
		1: "RATING_ONE",
		2: "RATING_TWO",
		3: "RATING_THREE",
		4: "RATING_FOUR",
		5: "RATING_FIVE",
	}
	Rating_value = map[string]int32{
		"RATING_UNSPECIFIED": 0,
		"RATING_ONE":         1,
		"RATING_TWO":         2,
		"RATING_THREE":       3,
		"RATING_FOUR":        4,
		"RATING_FIVE":        5,
	}
)

func (x Rating) Enum() *Rating {
	p := new(Rating)
	*p = x
	return p
}

func (x Rating) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rating) Descriptor() protoreflect.EnumDescriptor {
	return file_order_order_proto_enumTypes[3].Descriptor()
}

func (Rating) Type() protoreflect.EnumType {
	return &file_order_order_proto_enumTypes[3]
}

func (x Rating) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rating.Descriptor instead.
func (Rating) EnumDescriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{3}
}

// Order messages
type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ShippingName    string                 `protobuf:"bytes,5,opt,name=shipping_name,json=shippingName,proto3" json:"shipping_name,omitempty"`
	ShippingEmail   string                 `protobuf:"bytes,6,opt,name=shipping_email,json=shippingEmail,proto3" json:"shipping_email,omitempty"`
	ShippingPhone   string                 `protobuf:"bytes,7,opt,name=shipping_phone,json=shippingPhone,proto3" json:"shipping_phone,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,8,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Payment         *Payment               `protobuf:"bytes,9,opt,name=payment,proto3" json:"payment,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetShippingName() string {
	if x != nil {
		return x.ShippingName
	}
	return ""
}

func (x *Order) GetShippingEmail() string {
	if x != nil {
		return x.ShippingEmail
	}
	return ""
}

func (x *Order) GetShippingPhone() string {
	if x != nil {
		return x.ShippingPhone
	}
	return ""
}

func (x *Order) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *Order) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Payment         *PaymentInfo           `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	ShippingName    string                 `protobuf:"bytes,4,opt,name=shipping_name,json=shippingName,proto3" json:"shipping_name,omitempty"`
	ShippingEmail   string                 `protobuf:"bytes,5,opt,name=shipping_email,json=shippingEmail,proto3" json:"shipping_email,omitempty"`
	ShippingPhone   string                 `protobuf:"bytes,6,opt,name=shipping_phone,json=shippingPhone,proto3" json:"shipping_phone,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,7,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreateOrderRequest) GetShippingName() string {
	if x != nil {
		return x.ShippingName
	}
	return ""
}

func (x *CreateOrderRequest) GetShippingEmail() string {
	if x != nil {
		return x.ShippingEmail
	}
	return ""
}

func (x *CreateOrderRequest) GetShippingPhone() string {
	if x != nil {
		return x.ShippingPhone
	}
	return ""
}

func (x *CreateOrderRequest) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        PaymentMethod          `protobuf:"varint,1,opt,name=method,proto3,enum=order.PaymentMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentInfo) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type ListUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserOrdersRequest) Reset() {
	*x = ListUserOrdersRequest{}
	mi := &file_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrdersRequest) ProtoMessage() {}

func (x *ListUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Payment messages
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,4,opt,name=method,proto3,enum=order.PaymentMethod" json:"method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=order.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentDate   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{8}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentDate
	}
	return nil
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,2,opt,name=method,proto3,enum=order.PaymentMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_order_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_order_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=order.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_order_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePaymentStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *UpdatePaymentStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_order_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{12}
}

func (x *PaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        Rating                 `protobuf:"varint,4,opt,name=rating,proto3,enum=order.Rating" json:"rating,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_order_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{13}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Review) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Review) GetRating() Rating {
	if x != nil {
		return x.Rating
	}
	return Rating_RATING_UNSPECIFIED
}

func (x *Review) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Review) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        Rating                 `protobuf:"varint,3,opt,name=rating,proto3,enum=order.Rating" json:"rating,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_order_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{14}
}

func (x *CreateReviewRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateReviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() Rating {
	if x != nil {
		return x.Rating
	}
	return Rating_RATING_UNSPECIFIED
}

func (x *CreateReviewRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewRequest) Reset() {
	*x = GetReviewRequest{}
	mi := &file_order_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewRequest) ProtoMessage() {}

func (x *GetReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewRequest.ProtoReflect.Descriptor instead.
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{15}
}

func (x *GetReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReviewsRequest) Reset() {
	*x = GetOrderReviewsRequest{}
	mi := &file_order_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReviewsRequest) ProtoMessage() {}

func (x *GetOrderReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderReviewsRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderReviewsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReviewsResponse) Reset() {
	*x = GetOrderReviewsResponse{}
	mi := &file_order_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReviewsResponse) ProtoMessage() {}

func (x *GetOrderReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderReviewsResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{17}
}

func (x *GetOrderReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_order_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_order_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{19}
}

func (x *ReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

var File_order_order_proto protoreflect.FileDescriptor

const file_order_order_proto_rawDesc = "" +
	"\n" +
	"\x11order/order.proto\x12\x05order\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.order.OrderStatusR\x06status\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12#\n" +
	"\rshipping_name\x18\x05 \x01(\tR\fshippingName\x12%\n" +
	"\x0eshipping_email\x18\x06 \x01(\tR\rshippingEmail\x12%\n" +
	"\x0eshipping_phone\x18\a \x01(\tR\rshippingPhone\x12)\n" +
	"\x10shipping_address\x18\b \x01(\tR\x0fshippingAddress\x12(\n" +
	"\apayment\x18\t \x01(\v2\x0e.order.PaymentR\apayment\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x12,\n" +
	"\apayment\x18\x03 \x01(\v2\x12.order.PaymentInfoR\apayment\x12#\n" +
	"\rshipping_name\x18\x04 \x01(\tR\fshippingName\x12%\n" +
	"\x0eshipping_email\x18\x05 \x01(\tR\rshippingEmail\x12%\n" +
	"\x0eshipping_phone\x18\x06 \x01(\tR\rshippingPhone\x12)\n" +
	"\x10shipping_address\x18\a \x01(\tR\x0fshippingAddress\";\n" +
	"\vPaymentInfo\x12,\n" +
	"\x06method\x18\x01 \x01(\x0e2\x14.order.PaymentMethodR\x06method\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.order.OrderStatusR\x06status\"Z\n" +
	"\x15ListUserOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"P\n" +
	"\x12ListOrdersResponse\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"3\n" +
	"\rOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"\x84\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12,\n" +
	"\x06method\x18\x04 \x01(\x0e2\x14.order.PaymentMethodR\x06method\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.order.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12=\n" +
	"\fpayment_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vpaymentDate\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"`\n" +
	"\x15ProcessPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12,\n" +
	"\x06method\x18\x02 \x01(\x0e2\x14.order.PaymentMethodR\x06method\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.order.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\";\n" +
	"\x0fPaymentResponse\x12(\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.order.PaymentR\apayment\"\xce\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x06rating\x18\x04 \x01(\x0e2\r.order.RatingR\x06rating\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x127\n" +
	"\tcreate_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\"\x92\x01\n" +
	"\x13CreateReviewRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x06rating\x18\x03 \x01(\x0e2\r.order.RatingR\x06rating\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\"\n" +
	"\x10GetReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x16GetOrderReviewsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"B\n" +
	"\x17GetOrderReviewsResponse\x12'\n" +
	"\areviews\x18\x01 \x03(\v2\r.order.ReviewR\areviews\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x0eReviewResponse\x12%\n" +
	"\x06review\x18\x01 \x01(\v2\r.order.ReviewR\x06review*\xae\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_SHIPPED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05*\x9f\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_STATUS_SUCCESS\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x04*\xa7\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12\x19\n" +
	"\x15PAYMENT_METHOD_PAYPAL\x10\x03\x12\x1c\n" +
	"\x18PAYMENT_METHOD_BANK_WIRE\x10\x04*t\n" +
	"\x06Rating\x12\x16\n" +
	"\x12RATING_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"RATING_ONE\x10\x01\x12\x0e\n" +
	"\n" +
	"RATING_TWO\x10\x02\x12\x10\n" +
	"\fRATING_THREE\x10\x03\x12\x0f\n" +
	"\vRATING_FOUR\x10\x04\x12\x0f\n" +
	"\vRATING_FIVE\x10\x052\x97\x06\n" +
	"\fOrderService\x12>\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x14.order.OrderResponse\x12<\n" +
	"\fGetOrderByID\x12\x16.order.GetOrderRequest\x1a\x14.order.OrderResponse\x12J\n" +
	"\x11UpdateOrderStatus\x12\x1f.order.UpdateOrderStatusRequest\x1a\x14.order.OrderResponse\x12I\n" +
	"\x0eListUserOrders\x12\x1c.order.ListUserOrdersRequest\x1a\x19.order.ListOrdersResponse\x12F\n" +
	"\x0eProcessPayment\x12\x1c.order.ProcessPaymentRequest\x1a\x16.order.PaymentResponse\x12B\n" +
	"\x0eGetPaymentByID\x12\x18.order.GetPaymentRequest\x1a\x16.order.PaymentResponse\x12P\n" +
	"\x13UpdatePaymentStatus\x12!.order.UpdatePaymentStatusRequest\x1a\x16.order.PaymentResponse\x12A\n" +
	"\fCreateReview\x12\x1a.order.CreateReviewRequest\x1a\x15.order.ReviewResponse\x12;\n" +
	"\tGetReview\x12\x17.order.GetReviewRequest\x1a\x15.order.ReviewResponse\x12P\n" +
	"\x0fGetOrderReviews\x12\x1d.order.GetOrderReviewsRequest\x1a\x1e.order.GetOrderReviewsResponse\x12B\n" +
	"\fDeleteReview\x12\x1a.order.DeleteReviewRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/baccala1010/e-commerce/order/pkg/pbb\x06proto3"

var (
	file_order_order_proto_rawDescOnce sync.Once
	file_order_order_proto_rawDescData []byte
)

func file_order_order_proto_rawDescGZIP() []byte {
	file_order_order_proto_rawDescOnce.Do(func() {
		file_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)))
	})
	return file_order_order_proto_rawDescData
}

var file_order_order_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_order_order_proto_goTypes = []any{
	(OrderStatus)(0),                   // 0: order.OrderStatus
	(PaymentStatus)(0),                 // 1: order.PaymentStatus
	(PaymentMethod)(0),                 // 2: order.PaymentMethod
	(Rating)(0),                        // 3: order.Rating
	(*Order)(nil),                      // 4: order.Order
	(*CreateOrderRequest)(nil),         // 5: order.CreateOrderRequest
	(*PaymentInfo)(nil),                // 6: order.PaymentInfo
	(*GetOrderRequest)(nil),            // 7: order.GetOrderRequest
	(*UpdateOrderStatusRequest)(nil),   // 8: order.UpdateOrderStatusRequest
	(*ListUserOrdersRequest)(nil),      // 9: order.ListUserOrdersRequest
	(*ListOrdersResponse)(nil),         // 10: order.ListOrdersResponse
	(*OrderResponse)(nil),              // 11: order.OrderResponse
	(*Payment)(nil),                    // 12: order.Payment
	(*ProcessPaymentRequest)(nil),      // 13: order.ProcessPaymentRequest
	(*GetPaymentRequest)(nil),          // 14: order.GetPaymentRequest
	(*UpdatePaymentStatusRequest)(nil), // 15: order.UpdatePaymentStatusRequest
	(*PaymentResponse)(nil),            // 16: order.PaymentResponse
	(*Review)(nil),                     // 17: order.Review
	(*CreateReviewRequest)(nil),        // 18: order.CreateReviewRequest
	(*GetReviewRequest)(nil),           // 19: order.GetReviewRequest
	(*GetOrderReviewsRequest)(nil),     // 20: order.GetOrderReviewsRequest
	(*GetOrderReviewsResponse)(nil),    // 21: order.GetOrderReviewsResponse
	(*DeleteReviewRequest)(nil),        // 22: order.DeleteReviewRequest
	(*ReviewResponse)(nil),             // 23: order.ReviewResponse
	(*timestamppb.Timestamp)(nil),      // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 25: google.protobuf.Empty
}
var file_order_order_proto_depIdxs = []int32{
	0,  // 0: order.Order.status:type_name -> order.OrderStatus
	12, // 1: order.Order.payment:type_name -> order.Payment
	24, // 2: order.Order.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: order.Order.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 4: order.CreateOrderRequest.payment:type_name -> order.PaymentInfo
	2,  // 5: order.PaymentInfo.method:type_name -> order.PaymentMethod
	0,  // 6: order.UpdateOrderStatusRequest.status:type_name -> order.OrderStatus
	4,  // 7: order.ListOrdersResponse.orders:type_name -> order.Order
	4,  // 8: order.OrderResponse.order:type_name -> order.Order
	2,  // 9: order.Payment.method:type_name -> order.PaymentMethod
	1,  // 10: order.Payment.status:type_name -> order.PaymentStatus
	24, // 11: order.Payment.payment_date:type_name -> google.protobuf.Timestamp
	24, // 12: order.Payment.created_at:type_name -> google.protobuf.Timestamp
	24, // 13: order.Payment.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 14: order.ProcessPaymentRequest.method:type_name -> order.PaymentMethod
	1,  // 15: order.UpdatePaymentStatusRequest.status:type_name -> order.PaymentStatus
	12, // 16: order.PaymentResponse.payment:type_name -> order.Payment
	3,  // 17: order.Review.rating:type_name -> order.Rating
	24, // 18: order.Review.create_at:type_name -> google.protobuf.Timestamp
	3,  // 19: order.CreateReviewRequest.rating:type_name -> order.Rating
	17, // 20: order.GetOrderReviewsResponse.reviews:type_name -> order.Review
	17, // 21: order.ReviewResponse.review:type_name -> order.Review
	5,  // 22: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	7,  // 23: order.OrderService.GetOrderByID:input_type -> order.GetOrderRequest
	8,  // 24: order.OrderService.UpdateOrderStatus:input_type -> order.UpdateOrderStatusRequest
	9,  // 25: order.OrderService.ListUserOrders:input_type -> order.ListUserOrdersRequest
	13, // 26: order.OrderService.ProcessPayment:input_type -> order.ProcessPaymentRequest
	14, // 27: order.OrderService.GetPaymentByID:input_type -> order.GetPaymentRequest
	15, // 28: order.OrderService.UpdatePaymentStatus:input_type -> order.UpdatePaymentStatusRequest
	18, // 29: order.OrderService.CreateReview:input_type -> order.CreateReviewRequest
	19, // 30: order.OrderService.GetReview:input_type -> order.GetReviewRequest
	20, // 31: order.OrderService.GetOrderReviews:input_type -> order.GetOrderReviewsRequest
	22, // 32: order.OrderService.DeleteReview:input_type -> order.DeleteReviewRequest
	11, // 33: order.OrderService.CreateOrder:output_type -> order.OrderResponse
	11, // 34: order.OrderService.GetOrderByID:output_type -> order.OrderResponse
	11, // 35: order.OrderService.UpdateOrderStatus:output_type -> order.OrderResponse
	10, // 36: order.OrderService.ListUserOrders:output_type -> order.ListOrdersResponse
	16, // 37: order.OrderService.ProcessPayment:output_type -> order.PaymentResponse
	16, // 38: order.OrderService.GetPaymentByID:output_type -> order.PaymentResponse
	16, // 39: order.OrderService.UpdatePaymentStatus:output_type -> order.PaymentResponse
	23, // 40: order.OrderService.CreateReview:output_type -> order.ReviewResponse
	23, // 41: order.OrderService.GetReview:output_type -> order.ReviewResponse
	21, // 42: order.OrderService.GetOrderReviews:output_type -> order.GetOrderReviewsResponse
	25, // 43: order.OrderService.DeleteReview:output_type -> google.protobuf.Empty
	33, // [33:44] is the sub-list for method output_type
	22, // [22:33] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_order_order_proto_init() }
func file_order_order_proto_init() {
	if File_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_proto_goTypes,
		DependencyIndexes: file_order_order_proto_depIdxs,
		EnumInfos:         file_order_order_proto_enumTypes,
		MessageInfos:      file_order_order_proto_msgTypes,
	}.Build()
	File_order_order_proto = out.File
	file_order_order_proto_goTypes = nil
	file_order_order_proto_depIdxs = nil
}
