server:
  port: 8080
  name: "api-gateway"

services:
  inventory:
    base_url: "http://localhost:8081"
    grpc_host: "localhost"
    grpc_port: 9081
  order:
    base_url: "http://localhost:8083"
    grpc_host: "localhost"
    grpc_port: 9082

logging:
  level: "debug" 
