grpc:
  port: 50053
kafka:
  brokers:
    - kafka:9092
  group_id: statistics-group
  topics:
    - order-events
    - inventory-events
database:
  host: statistics-postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: statistics_db
