grpc:
  port: 50053
kafka:
  brokers:
    - localhost:9092
  group_id: statistics-group
  topics:
    - order-events
    - inventory-events
database:
  host: localhost
  port: 5434
  user: postgres
  password: postgres
  dbname: statistics_db
