server:
  port: 8081
  name: "inventory-service"

database:
  host: "postgres"
  port: 5432
  name: "inventory_db"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"
  max_idle_connections: 10
  max_open_connections: 100
  connection_max_lifetime: "1h"

logging:
  level: "debug" 