server:
  port: 8083
  grpc_port: 9082
  name: "order-service"

database:
  host: "localhost"
  port: 5432
  name: "order_db"
  username: "postgres"
  password: "postgres"
  sslmode: "disable"
  max_idle_connections: 10
  max_open_connections: 100
  connection_max_lifetime: "1h"

inventory_service:
  base_url: "http://localhost:8081"

kafka:
  bootstrap_servers: "localhost:9092"
  topics:
    order_events: "order-events"
    user_events: "user-events"

logging:
  level: "debug" 
